export const REVEAL_TILE = 'REVEAL_TILE';
export const TOGGLE_FLAG = 'TOGGLE_FLAG';
export const GAME_OVER = 'GAME_OVER';
export const RESTART_GAME = 'RESTART_GAME';
export const CHANGE_DIFFICULTY_EASY = 'CHANGE_DIFFICULTY_EASY';
export const CHANGE_DIFFICULTY_NORMAL = 'CHANGE_DIFFICULTY_NORMAL';
export const CHANGE_DIFFICULTY_HARD = 'CHANGE_DIFFICULTY_HARD';

export const TIMER_START = 'TIMER_START';
export const TIMER_STOP = 'TIMER_STOP';
export const TIMER_TICK = 'TIMER_TICK';